// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.daykm.p5executioner.data;

public final class Data {
	private Data() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public interface ComboOrBuilder extends
			// @@protoc_insertion_point(interface_extends:p5.Combo)
			com.google.protobuf.MessageLiteOrBuilder {

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		java.util.List<String> getSourcesList();

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		int getSourcesCount();

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		String getSources(int index);

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		com.google.protobuf.ByteString getSourcesBytes(int index);

		/**
		 * <code>string arcana = 2;</code>
		 */
		String getArcana();

		/**
		 * <code>string arcana = 2;</code>
		 */
		com.google.protobuf.ByteString getArcanaBytes();
	}

	/**
	 * Protobuf type {@code p5.Combo}
	 */
	public static final class Combo
			extends com.google.protobuf.GeneratedMessageLite<Combo, Combo.Builder> implements
			// @@protoc_insertion_point(message_implements:p5.Combo)
			ComboOrBuilder {
		private Combo() {
			sources_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
			arcana_ = "";
		}

		private int bitField0_;
		public static final int SOURCES_FIELD_NUMBER = 1;
		private com.google.protobuf.Internal.ProtobufList<String> sources_;

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		public java.util.List<String> getSourcesList() {
			return sources_;
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		public int getSourcesCount() {
			return sources_.size();
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		public String getSources(int index) {
			return sources_.get(index);
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		public com.google.protobuf.ByteString getSourcesBytes(int index) {
			return com.google.protobuf.ByteString.copyFromUtf8(sources_.get(index));
		}

		private void ensureSourcesIsMutable() {
			if (!sources_.isModifiable()) {
				sources_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(sources_);
			}
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		private void setSources(int index, String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureSourcesIsMutable();
			sources_.set(index, value);
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		private void addSources(String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureSourcesIsMutable();
			sources_.add(value);
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		private void addAllSources(Iterable<String> values) {
			ensureSourcesIsMutable();
			com.google.protobuf.AbstractMessageLite.addAll(values, sources_);
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		private void clearSources() {
			sources_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
		}

		/**
		 * <code>repeated string sources = 1;</code>
		 */
		private void addSourcesBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			ensureSourcesIsMutable();
			sources_.add(value.toStringUtf8());
		}

		public static final int ARCANA_FIELD_NUMBER = 2;
		private String arcana_;

		/**
		 * <code>string arcana = 2;</code>
		 */
		public String getArcana() {
			return arcana_;
		}

		/**
		 * <code>string arcana = 2;</code>
		 */
		public com.google.protobuf.ByteString getArcanaBytes() {
			return com.google.protobuf.ByteString.copyFromUtf8(arcana_);
		}

		/**
		 * <code>string arcana = 2;</code>
		 */
		private void setArcana(String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			arcana_ = value;
		}

		/**
		 * <code>string arcana = 2;</code>
		 */
		private void clearArcana() {

			arcana_ = getDefaultInstance().getArcana();
		}

		/**
		 * <code>string arcana = 2;</code>
		 */
		private void setArcanaBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			arcana_ = value.toStringUtf8();
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (int i = 0; i < sources_.size(); i++) {
				output.writeString(1, sources_.get(i));
			}
			if (!arcana_.isEmpty()) {
				output.writeString(2, getArcana());
			}
		}

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			{
				int dataSize = 0;
				for (int i = 0; i < sources_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeStringSizeNoTag(sources_.get(i));
				}
				size += dataSize;
				size += 1 * getSourcesList().size();
			}
			if (!arcana_.isEmpty()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(2, getArcana());
			}
			memoizedSerializedSize = size;
			return size;
		}

		public static Combo parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static Combo parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static Combo parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static Combo parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static Combo parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static Combo parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Combo parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input);
		}

		public static Combo parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static Combo parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static Combo parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Combo prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		/**
		 * Protobuf type {@code p5.Combo}
		 */
		public static final class Builder
				extends com.google.protobuf.GeneratedMessageLite.Builder<Combo, Builder> implements
				// @@protoc_insertion_point(builder_implements:p5.Combo)
				ComboOrBuilder {
			// Construct using com.daykm.p5executioner.data.Data.Combo.newBuilder()
			private Builder() {
				super(DEFAULT_INSTANCE);
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public java.util.List<String> getSourcesList() {
				return java.util.Collections.unmodifiableList(instance.getSourcesList());
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public int getSourcesCount() {
				return instance.getSourcesCount();
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public String getSources(int index) {
				return instance.getSources(index);
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public com.google.protobuf.ByteString getSourcesBytes(int index) {
				return instance.getSourcesBytes(index);
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public Builder setSources(int index, String value) {
				copyOnWrite();
				instance.setSources(index, value);
				return this;
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public Builder addSources(String value) {
				copyOnWrite();
				instance.addSources(value);
				return this;
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public Builder addAllSources(Iterable<String> values) {
				copyOnWrite();
				instance.addAllSources(values);
				return this;
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public Builder clearSources() {
				copyOnWrite();
				instance.clearSources();
				return this;
			}

			/**
			 * <code>repeated string sources = 1;</code>
			 */
			public Builder addSourcesBytes(com.google.protobuf.ByteString value) {
				copyOnWrite();
				instance.addSourcesBytes(value);
				return this;
			}

			/**
			 * <code>string arcana = 2;</code>
			 */
			public String getArcana() {
				return instance.getArcana();
			}

			/**
			 * <code>string arcana = 2;</code>
			 */
			public com.google.protobuf.ByteString getArcanaBytes() {
				return instance.getArcanaBytes();
			}

			/**
			 * <code>string arcana = 2;</code>
			 */
			public Builder setArcana(String value) {
				copyOnWrite();
				instance.setArcana(value);
				return this;
			}

			/**
			 * <code>string arcana = 2;</code>
			 */
			public Builder clearArcana() {
				copyOnWrite();
				instance.clearArcana();
				return this;
			}

			/**
			 * <code>string arcana = 2;</code>
			 */
			public Builder setArcanaBytes(com.google.protobuf.ByteString value) {
				copyOnWrite();
				instance.setArcanaBytes(value);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:p5.Combo)
		}

		protected final Object dynamicMethod(MethodToInvoke method, Object arg0, Object arg1) {
			switch (method) {
				case NEW_MUTABLE_INSTANCE: {
					return new Combo();
				}
				case IS_INITIALIZED: {
					return DEFAULT_INSTANCE;
				}
				case MAKE_IMMUTABLE: {
					sources_.makeImmutable();
					return null;
				}
				case NEW_BUILDER: {
					return new Builder();
				}
				case VISIT: {
					Visitor visitor = (Visitor) arg0;
					Combo other = (Combo) arg1;
					sources_ = visitor.visitList(sources_, other.sources_);
					arcana_ = visitor.visitString(!arcana_.isEmpty(), arcana_, !other.arcana_.isEmpty(),
							other.arcana_);
					if (visitor == MergeFromVisitor.INSTANCE) {
						bitField0_ |= other.bitField0_;
					}
					return this;
				}
				case MERGE_FROM_STREAM: {
					com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
					com.google.protobuf.ExtensionRegistryLite extensionRegistry =
							(com.google.protobuf.ExtensionRegistryLite) arg1;
					try {
						boolean done = false;
						while (!done) {
							int tag = input.readTag();
							switch (tag) {
								case 0:
									done = true;
									break;
								default: {
									if (!input.skipField(tag)) {
										done = true;
									}
									break;
								}
								case 10: {
									String s = input.readStringRequireUtf8();
									if (!sources_.isModifiable()) {
										sources_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(sources_);
									}
									sources_.add(s);
									break;
								}
								case 18: {
									String s = input.readStringRequireUtf8();

									arcana_ = s;
									break;
								}
							}
						}
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						throw new RuntimeException(e.setUnfinishedMessage(this));
					} catch (java.io.IOException e) {
						throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(
								e.getMessage()).setUnfinishedMessage(this));
					} finally {
					}
				}
				case GET_DEFAULT_INSTANCE: {
					return DEFAULT_INSTANCE;
				}
				case GET_PARSER: {
					if (PARSER == null) {
						synchronized (Combo.class) {
							if (PARSER == null) {
								PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
							}
						}
					}
					return PARSER;
				}
			}
			throw new UnsupportedOperationException();
		}

		// @@protoc_insertion_point(class_scope:p5.Combo)
		private static final Combo DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Combo();
			DEFAULT_INSTANCE.makeImmutable();
		}

		public static Combo getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static volatile com.google.protobuf.Parser<Combo> PARSER;

		public static com.google.protobuf.Parser<Combo> parser() {
			return DEFAULT_INSTANCE.getParserForType();
		}
	}

	public interface CombosOrBuilder extends
			// @@protoc_insertion_point(interface_extends:p5.Combos)
			com.google.protobuf.MessageLiteOrBuilder {

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		java.util.List<Combo> getListList();

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		Combo getList(int index);

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		int getListCount();
	}

	/**
	 * Protobuf type {@code p5.Combos}
	 */
	public static final class Combos
			extends com.google.protobuf.GeneratedMessageLite<Combos, Combos.Builder> implements
			// @@protoc_insertion_point(message_implements:p5.Combos)
			CombosOrBuilder {
		private Combos() {
			list_ = emptyProtobufList();
		}

		public static final int LIST_FIELD_NUMBER = 1;
		private com.google.protobuf.Internal.ProtobufList<Combo> list_;

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		public java.util.List<Combo> getListList() {
			return list_;
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		public java.util.List<? extends ComboOrBuilder> getListOrBuilderList() {
			return list_;
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		public int getListCount() {
			return list_.size();
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		public Combo getList(int index) {
			return list_.get(index);
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		public ComboOrBuilder getListOrBuilder(int index) {
			return list_.get(index);
		}

		private void ensureListIsMutable() {
			if (!list_.isModifiable()) {
				list_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(list_);
			}
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void setList(int index, Combo value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureListIsMutable();
			list_.set(index, value);
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void setList(int index, Combo.Builder builderForValue) {
			ensureListIsMutable();
			list_.set(index, builderForValue.build());
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void addList(Combo value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureListIsMutable();
			list_.add(value);
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void addList(int index, Combo value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureListIsMutable();
			list_.add(index, value);
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void addList(Combo.Builder builderForValue) {
			ensureListIsMutable();
			list_.add(builderForValue.build());
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void addList(int index, Combo.Builder builderForValue) {
			ensureListIsMutable();
			list_.add(index, builderForValue.build());
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void addAllList(Iterable<? extends Combo> values) {
			ensureListIsMutable();
			com.google.protobuf.AbstractMessageLite.addAll(values, list_);
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void clearList() {
			list_ = emptyProtobufList();
		}

		/**
		 * <code>repeated .p5.Combo list = 1;</code>
		 */
		private void removeList(int index) {
			ensureListIsMutable();
			list_.remove(index);
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
		}

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, list_.get(i));
			}
			memoizedSerializedSize = size;
			return size;
		}

		public static Combos parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static Combos parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static Combos parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static Combos parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static Combos parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static Combos parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Combos parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input);
		}

		public static Combos parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static Combos parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static Combos parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Combos prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		/**
		 * Protobuf type {@code p5.Combos}
		 */
		public static final class Builder
				extends com.google.protobuf.GeneratedMessageLite.Builder<Combos, Builder> implements
				// @@protoc_insertion_point(builder_implements:p5.Combos)
				CombosOrBuilder {
			// Construct using com.daykm.p5executioner.data.Data.Combos.newBuilder()
			private Builder() {
				super(DEFAULT_INSTANCE);
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public java.util.List<Combo> getListList() {
				return java.util.Collections.unmodifiableList(instance.getListList());
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public int getListCount() {
				return instance.getListCount();
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Combo getList(int index) {
				return instance.getList(index);
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder setList(int index, Combo value) {
				copyOnWrite();
				instance.setList(index, value);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder setList(int index, Combo.Builder builderForValue) {
				copyOnWrite();
				instance.setList(index, builderForValue);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder addList(Combo value) {
				copyOnWrite();
				instance.addList(value);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder addList(int index, Combo value) {
				copyOnWrite();
				instance.addList(index, value);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder addList(Combo.Builder builderForValue) {
				copyOnWrite();
				instance.addList(builderForValue);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder addList(int index, Combo.Builder builderForValue) {
				copyOnWrite();
				instance.addList(index, builderForValue);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder addAllList(Iterable<? extends Combo> values) {
				copyOnWrite();
				instance.addAllList(values);
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder clearList() {
				copyOnWrite();
				instance.clearList();
				return this;
			}

			/**
			 * <code>repeated .p5.Combo list = 1;</code>
			 */
			public Builder removeList(int index) {
				copyOnWrite();
				instance.removeList(index);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:p5.Combos)
		}

		protected final Object dynamicMethod(MethodToInvoke method, Object arg0, Object arg1) {
			switch (method) {
				case NEW_MUTABLE_INSTANCE: {
					return new Combos();
				}
				case IS_INITIALIZED: {
					return DEFAULT_INSTANCE;
				}
				case MAKE_IMMUTABLE: {
					list_.makeImmutable();
					return null;
				}
				case NEW_BUILDER: {
					return new Builder();
				}
				case VISIT: {
					Visitor visitor = (Visitor) arg0;
					Combos other = (Combos) arg1;
					list_ = visitor.visitList(list_, other.list_);
					if (visitor == MergeFromVisitor.INSTANCE) {
					}
					return this;
				}
				case MERGE_FROM_STREAM: {
					com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
					com.google.protobuf.ExtensionRegistryLite extensionRegistry =
							(com.google.protobuf.ExtensionRegistryLite) arg1;
					try {
						boolean done = false;
						while (!done) {
							int tag = input.readTag();
							switch (tag) {
								case 0:
									done = true;
									break;
								default: {
									if (!input.skipField(tag)) {
										done = true;
									}
									break;
								}
								case 10: {
									if (!list_.isModifiable()) {
										list_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(list_);
									}
									list_.add(input.readMessage(Combo.parser(), extensionRegistry));
									break;
								}
							}
						}
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						throw new RuntimeException(e.setUnfinishedMessage(this));
					} catch (java.io.IOException e) {
						throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(
								e.getMessage()).setUnfinishedMessage(this));
					} finally {
					}
				}
				case GET_DEFAULT_INSTANCE: {
					return DEFAULT_INSTANCE;
				}
				case GET_PARSER: {
					if (PARSER == null) {
						synchronized (Combos.class) {
							if (PARSER == null) {
								PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
							}
						}
					}
					return PARSER;
				}
			}
			throw new UnsupportedOperationException();
		}

		// @@protoc_insertion_point(class_scope:p5.Combos)
		private static final Combos DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Combos();
			DEFAULT_INSTANCE.makeImmutable();
		}

		public static Combos getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static volatile com.google.protobuf.Parser<Combos> PARSER;

		public static com.google.protobuf.Parser<Combos> parser() {
			return DEFAULT_INSTANCE.getParserForType();
		}
	}

	public interface RareComboOrBuilder extends
			// @@protoc_insertion_point(interface_extends:p5.RareCombo)
			com.google.protobuf.MessageLiteOrBuilder {

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		java.util.List<Integer> getCombosList();

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		int getCombosCount();

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		int getCombos(int index);
	}

	/**
	 * Protobuf type {@code p5.RareCombo}
	 */
	public static final class RareCombo
			extends com.google.protobuf.GeneratedMessageLite<RareCombo, RareCombo.Builder> implements
			// @@protoc_insertion_point(message_implements:p5.RareCombo)
			RareComboOrBuilder {
		private RareCombo() {
			combos_ = emptyIntList();
		}

		public static final int COMBOS_FIELD_NUMBER = 1;
		private com.google.protobuf.Internal.IntList combos_;

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		public java.util.List<Integer> getCombosList() {
			return combos_;
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		public int getCombosCount() {
			return combos_.size();
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		public int getCombos(int index) {
			return combos_.getInt(index);
		}

		private void ensureCombosIsMutable() {
			if (!combos_.isModifiable()) {
				combos_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(combos_);
			}
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		private void setCombos(int index, int value) {
			ensureCombosIsMutable();
			combos_.setInt(index, value);
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		private void addCombos(int value) {
			ensureCombosIsMutable();
			combos_.addInt(value);
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		private void addAllCombos(Iterable<? extends Integer> values) {
			ensureCombosIsMutable();
			com.google.protobuf.AbstractMessageLite.addAll(values, combos_);
		}

		/**
		 * <code>repeated sint32 combos = 1;</code>
		 */
		private void clearCombos() {
			combos_ = emptyIntList();
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < combos_.size(); i++) {
				output.writeSInt32(1, combos_.getInt(i));
			}
		}

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			{
				int dataSize = 0;
				for (int i = 0; i < combos_.size(); i++) {
					dataSize +=
							com.google.protobuf.CodedOutputStream.computeSInt32SizeNoTag(combos_.getInt(i));
				}
				size += dataSize;
				size += 1 * getCombosList().size();
			}
			memoizedSerializedSize = size;
			return size;
		}

		public static RareCombo parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static RareCombo parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static RareCombo parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static RareCombo parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static RareCombo parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombo parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static RareCombo parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombo parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static RareCombo parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombo parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(RareCombo prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		/**
		 * Protobuf type {@code p5.RareCombo}
		 */
		public static final class Builder
				extends com.google.protobuf.GeneratedMessageLite.Builder<RareCombo, Builder> implements
				// @@protoc_insertion_point(builder_implements:p5.RareCombo)
				RareComboOrBuilder {
			// Construct using com.daykm.p5executioner.data.Data.RareCombo.newBuilder()
			private Builder() {
				super(DEFAULT_INSTANCE);
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public java.util.List<Integer> getCombosList() {
				return java.util.Collections.unmodifiableList(instance.getCombosList());
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public int getCombosCount() {
				return instance.getCombosCount();
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public int getCombos(int index) {
				return instance.getCombos(index);
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public Builder setCombos(int index, int value) {
				copyOnWrite();
				instance.setCombos(index, value);
				return this;
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public Builder addCombos(int value) {
				copyOnWrite();
				instance.addCombos(value);
				return this;
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public Builder addAllCombos(Iterable<? extends Integer> values) {
				copyOnWrite();
				instance.addAllCombos(values);
				return this;
			}

			/**
			 * <code>repeated sint32 combos = 1;</code>
			 */
			public Builder clearCombos() {
				copyOnWrite();
				instance.clearCombos();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:p5.RareCombo)
		}

		protected final Object dynamicMethod(MethodToInvoke method, Object arg0, Object arg1) {
			switch (method) {
				case NEW_MUTABLE_INSTANCE: {
					return new RareCombo();
				}
				case IS_INITIALIZED: {
					return DEFAULT_INSTANCE;
				}
				case MAKE_IMMUTABLE: {
					combos_.makeImmutable();
					return null;
				}
				case NEW_BUILDER: {
					return new Builder();
				}
				case VISIT: {
					Visitor visitor = (Visitor) arg0;
					RareCombo other = (RareCombo) arg1;
					combos_ = visitor.visitIntList(combos_, other.combos_);
					if (visitor == MergeFromVisitor.INSTANCE) {
					}
					return this;
				}
				case MERGE_FROM_STREAM: {
					com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
					com.google.protobuf.ExtensionRegistryLite extensionRegistry =
							(com.google.protobuf.ExtensionRegistryLite) arg1;
					try {
						boolean done = false;
						while (!done) {
							int tag = input.readTag();
							switch (tag) {
								case 0:
									done = true;
									break;
								default: {
									if (!input.skipField(tag)) {
										done = true;
									}
									break;
								}
								case 8: {
									if (!combos_.isModifiable()) {
										combos_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(combos_);
									}
									combos_.addInt(input.readSInt32());
									break;
								}
								case 10: {
									int length = input.readRawVarint32();
									int limit = input.pushLimit(length);
									if (!combos_.isModifiable() && input.getBytesUntilLimit() > 0) {
										combos_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(combos_);
									}
									while (input.getBytesUntilLimit() > 0) {
										combos_.addInt(input.readSInt32());
									}
									input.popLimit(limit);
									break;
								}
							}
						}
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						throw new RuntimeException(e.setUnfinishedMessage(this));
					} catch (java.io.IOException e) {
						throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(
								e.getMessage()).setUnfinishedMessage(this));
					} finally {
					}
				}
				case GET_DEFAULT_INSTANCE: {
					return DEFAULT_INSTANCE;
				}
				case GET_PARSER: {
					if (PARSER == null) {
						synchronized (RareCombo.class) {
							if (PARSER == null) {
								PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
							}
						}
					}
					return PARSER;
				}
			}
			throw new UnsupportedOperationException();
		}

		// @@protoc_insertion_point(class_scope:p5.RareCombo)
		private static final RareCombo DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new RareCombo();
			DEFAULT_INSTANCE.makeImmutable();
		}

		public static RareCombo getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static volatile com.google.protobuf.Parser<RareCombo> PARSER;

		public static com.google.protobuf.Parser<RareCombo> parser() {
			return DEFAULT_INSTANCE.getParserForType();
		}
	}

	public interface RareCombosOrBuilder extends
			// @@protoc_insertion_point(interface_extends:p5.RareCombos)
			com.google.protobuf.MessageLiteOrBuilder {

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */
		int getCombosCount();

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */
		boolean containsCombos(String key);

		/**
		 * Use {@link #getCombosMap()} instead.
		 */
		@Deprecated java.util.Map<String, RareCombo> getCombos();

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */
		java.util.Map<String, RareCombo> getCombosMap();

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		RareCombo getCombosOrDefault(String key, RareCombo defaultValue);

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		RareCombo getCombosOrThrow(String key);
	}

	/**
	 * Protobuf type {@code p5.RareCombos}
	 */
	public static final class RareCombos
			extends com.google.protobuf.GeneratedMessageLite<RareCombos, RareCombos.Builder> implements
			// @@protoc_insertion_point(message_implements:p5.RareCombos)
			RareCombosOrBuilder {
		private RareCombos() {
		}

		public static final int COMBOS_FIELD_NUMBER = 1;

		private static final class CombosDefaultEntryHolder {
			static final com.google.protobuf.MapEntryLite<String, RareCombo> defaultEntry =
					com.google.protobuf.MapEntryLite.<String, RareCombo>newDefaultInstance(
							com.google.protobuf.WireFormat.FieldType.STRING, "",
							com.google.protobuf.WireFormat.FieldType.MESSAGE, RareCombo.getDefaultInstance());
		}

		private com.google.protobuf.MapFieldLite<String, RareCombo> combos_ =
				com.google.protobuf.MapFieldLite.emptyMapField();

		private com.google.protobuf.MapFieldLite<String, RareCombo> internalGetCombos() {
			return combos_;
		}

		private com.google.protobuf.MapFieldLite<String, RareCombo> internalGetMutableCombos() {
			if (!combos_.isMutable()) {
				combos_ = combos_.mutableCopy();
			}
			return combos_;
		}

		public int getCombosCount() {
			return internalGetCombos().size();
		}

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		public boolean containsCombos(String key) {
			if (key == null) {
				throw new NullPointerException();
			}
			return internalGetCombos().containsKey(key);
		}

		/**
		 * Use {@link #getCombosMap()} instead.
		 */
		@Deprecated public java.util.Map<String, RareCombo> getCombos() {
			return getCombosMap();
		}

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		public java.util.Map<String, RareCombo> getCombosMap() {
			return java.util.Collections.unmodifiableMap(internalGetCombos());
		}

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		public RareCombo getCombosOrDefault(String key, RareCombo defaultValue) {
			if (key == null) {
				throw new NullPointerException();
			}
			java.util.Map<String, RareCombo> map = internalGetCombos();
			return map.containsKey(key) ? map.get(key) : defaultValue;
		}

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */

		public RareCombo getCombosOrThrow(String key) {
			if (key == null) {
				throw new NullPointerException();
			}
			java.util.Map<String, RareCombo> map = internalGetCombos();
			if (!map.containsKey(key)) {
				throw new IllegalArgumentException();
			}
			return map.get(key);
		}

		/**
		 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
		 */
		private java.util.Map<String, RareCombo> getMutableCombosMap() {
			return internalGetMutableCombos();
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (java.util.Map.Entry<String, RareCombo> entry : internalGetCombos().entrySet()) {
				CombosDefaultEntryHolder.defaultEntry.serializeTo(output, 1, entry.getKey(),
						entry.getValue());
			}
		}

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			for (java.util.Map.Entry<String, RareCombo> entry : internalGetCombos().entrySet()) {
				size += CombosDefaultEntryHolder.defaultEntry.computeMessageSize(1, entry.getKey(),
						entry.getValue());
			}
			memoizedSerializedSize = size;
			return size;
		}

		public static RareCombos parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static RareCombos parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static RareCombos parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static RareCombos parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data,
					extensionRegistry);
		}

		public static RareCombos parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombos parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static RareCombos parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombos parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static RareCombos parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static RareCombos parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(RareCombos prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		/**
		 * Protobuf type {@code p5.RareCombos}
		 */
		public static final class Builder
				extends com.google.protobuf.GeneratedMessageLite.Builder<RareCombos, Builder> implements
				// @@protoc_insertion_point(builder_implements:p5.RareCombos)
				RareCombosOrBuilder {
			// Construct using com.daykm.p5executioner.data.Data.RareCombos.newBuilder()
			private Builder() {
				super(DEFAULT_INSTANCE);
			}

			public int getCombosCount() {
				return instance.getCombosMap().size();
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */

			public boolean containsCombos(String key) {
				if (key == null) {
					throw new NullPointerException();
				}
				return instance.getCombosMap().containsKey(key);
			}

			public Builder clearCombos() {
				copyOnWrite();
				instance.getMutableCombosMap().clear();
				return this;
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */

			public Builder removeCombos(String key) {
				if (key == null) {
					throw new NullPointerException();
				}
				copyOnWrite();
				instance.getMutableCombosMap().remove(key);
				return this;
			}

			/**
			 * Use {@link #getCombosMap()} instead.
			 */
			@Deprecated public java.util.Map<String, RareCombo> getCombos() {
				return getCombosMap();
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */
			public java.util.Map<String, RareCombo> getCombosMap() {
				return java.util.Collections.unmodifiableMap(instance.getCombosMap());
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */

			public RareCombo getCombosOrDefault(String key, RareCombo defaultValue) {
				if (key == null) {
					throw new NullPointerException();
				}
				java.util.Map<String, RareCombo> map = instance.getCombosMap();
				return map.containsKey(key) ? map.get(key) : defaultValue;
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */

			public RareCombo getCombosOrThrow(String key) {
				if (key == null) {
					throw new NullPointerException();
				}
				java.util.Map<String, RareCombo> map = instance.getCombosMap();
				if (!map.containsKey(key)) {
					throw new IllegalArgumentException();
				}
				return map.get(key);
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */
			public Builder putCombos(String key, RareCombo value) {
				if (key == null) {
					throw new NullPointerException();
				}
				if (value == null) {
					throw new NullPointerException();
				}
				copyOnWrite();
				instance.getMutableCombosMap().put(key, value);
				return this;
			}

			/**
			 * <code>map&lt;string, .p5.RareCombo&gt; combos = 1;</code>
			 */
			public Builder putAllCombos(java.util.Map<String, RareCombo> values) {
				copyOnWrite();
				instance.getMutableCombosMap().putAll(values);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:p5.RareCombos)
		}

		protected final Object dynamicMethod(MethodToInvoke method, Object arg0, Object arg1) {
			switch (method) {
				case NEW_MUTABLE_INSTANCE: {
					return new RareCombos();
				}
				case IS_INITIALIZED: {
					return DEFAULT_INSTANCE;
				}
				case MAKE_IMMUTABLE: {
					combos_.makeImmutable();
					return null;
				}
				case NEW_BUILDER: {
					return new Builder();
				}
				case VISIT: {
					Visitor visitor = (Visitor) arg0;
					RareCombos other = (RareCombos) arg1;
					combos_ = visitor.visitMap(combos_, other.internalGetCombos());
					if (visitor == MergeFromVisitor.INSTANCE) {
					}
					return this;
				}
				case MERGE_FROM_STREAM: {
					com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
					com.google.protobuf.ExtensionRegistryLite extensionRegistry =
							(com.google.protobuf.ExtensionRegistryLite) arg1;
					try {
						boolean done = false;
						while (!done) {
							int tag = input.readTag();
							switch (tag) {
								case 0:
									done = true;
									break;
								default: {
									if (!input.skipField(tag)) {
										done = true;
									}
									break;
								}
								case 10: {
									if (!combos_.isMutable()) {
										combos_ = combos_.mutableCopy();
									}
									CombosDefaultEntryHolder.defaultEntry.parseInto(combos_, input,
											extensionRegistry);
									break;
								}
							}
						}
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						throw new RuntimeException(e.setUnfinishedMessage(this));
					} catch (java.io.IOException e) {
						throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(
								e.getMessage()).setUnfinishedMessage(this));
					} finally {
					}
				}
				case GET_DEFAULT_INSTANCE: {
					return DEFAULT_INSTANCE;
				}
				case GET_PARSER: {
					if (PARSER == null) {
						synchronized (RareCombos.class) {
							if (PARSER == null) {
								PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
							}
						}
					}
					return PARSER;
				}
			}
			throw new UnsupportedOperationException();
		}

		// @@protoc_insertion_point(class_scope:p5.RareCombos)
		private static final RareCombos DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new RareCombos();
			DEFAULT_INSTANCE.makeImmutable();
		}

		public static RareCombos getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static volatile com.google.protobuf.Parser<RareCombos> PARSER;

		public static com.google.protobuf.Parser<RareCombos> parser() {
			return DEFAULT_INSTANCE.getParserForType();
		}
	}

	static {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
